# This is a sample build configuration for Haskell.
# Do not use tabs to indent your configuration
# You can specify a custom docker image from Dockerhub# for your build environment
image: haskell:8.0.2
pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y libpq-dev pkgconf
          - cabal update
          - cabal install --enable-tests --only-dependencies --force-reinstalls
          - cabal configure --enable-tests
          - cabal build
          - cabal test
