# This is a sample build configuration for Haskell.
# Do not use tabs to indent your configuration
# You can specify a custom docker image from Dockerhub# for your build environment
image: haskell:7.10.3
pipelines:
  default:
    - step:
        script:
          - cabal update
          - cabal install --verbose=3 --enable-tests --only-dependencies --force-reinstalls
          - cabal configure --verbose=3 --enable-tests
          - cabal build
          - cabal test
