# This is a sample build configuration for Haskell.
# Do not use tabs to indent your configuration
# You can specify a custom docker image from Dockerhub# for your build environment
image: zsol/haskell-platform-2014.2.0.0:latest
pipelines:
  default:
    - step:
        script:
          - cabal sandbox init
          - cabal update
          - cabal install --enable-tests --only-dependencies
          - cabal configure --enable-tests
          - cabal build
          - cabal test
