name: my-reminders
version: '0.28'
synopsis: My reminders plugin for Atlassian Cloud
description: Set issue reminders for the future!
category: Web
author: Robert Massaioli, Eero Kaukonen, Sidney Shek, Avi Knoll
maintainer: ekaukonen@atlassian.com
license: MIT
dependencies:
- snap-loader-static
executables:
  my-reminders:
    main: Main.hs
    source-dirs: src
    dependencies:
    - aeson >=0.8
    - atlassian-connect-core >=0.8.1.0 && <0.9
    - atlassian-connect-descriptor >=0.4.8
    - base >=4.6 && <5
    - base64-bytestring ==1.*
    - boxes ==0.1.*
    - bytestring >=0.9.1 && <0.11
    - case-insensitive ==1.*
    - cipher-aes ==0.2.*
    - configurator ==0.3.*
    - containers >=0.5 && <0.7
    - directory >=1.1 && <1.4
    - either >= 5
    - filepath ==1.4.*
    - heist >=1.0 && <1.2
    - hostname ==1.0
    - http-client >=0.5 && <0.7
    - http-types >= 0.8
    - jwt ==0.7.*
    - lens ==4.*
    - lifted-base ==0.2.*
    - map-syntax >=0.2 && <0.4
    - mtl ==2.*
    - mustache ==2.3.*
    - network >=2.6
    - network-api-support ==0.3.*
    - network-uri >=2.6
    - parallel-io ==0.3.*
    - postgresql-simple >=0.4
    - process >=1.4 && <1.7
    - resource-pool ==0.2.*
    - snap
    - snap-core ==1.0.*
    - snap-server
    - snaplet-postgresql-simple >=0.6.0.2
    - split ==0.2.*
    - stm >=2.4 && <3
    - tagsoup ==0.14.*
    - text ==1.2.*
    - time >=1.6 && <=1.11
    - time-units ==1.*
    - tls >=1.4.0
    - transformers >=0.4
    - utf8-string >=0.3.8
    - uuid ==1.3.*
    - xmlhtml ==0.2.*
    when:
    - condition: flag(development)
      then:
        ghc-options:
        - -threaded
        - -w
        cpp-options: -DDEVELOPMENT
        dependencies:
        - snap-loader-dynamic
      else:
        ghc-options:
        - -threaded
        - -Wall
        - -fwarn-tabs
        - -funbox-strict-fields
        - -O2
        - -fno-warn-orphans
        - -fno-warn-unused-do-bind
tests:
  my-reminders-props:
    main: TestRunner.hs
    source-dirs:
    - tests
    - src
    dependencies:
    - base
    - QuickCheck >=2.7
    - quickcheck-instances >=0.3
    - test-framework ==0.8.*
    - test-framework-quickcheck2 >=0.3
    - aeson
    - atlassian-connect-core
    - atlassian-connect-descriptor
    - base64-bytestring
    - boxes
    - bytestring
    - case-insensitive
    - cipher-aes
    - configurator
    - containers
    - directory
    - email-validate
    - filepath
    - mustache
    - heist
    - hostname
    - http-client
    - http-media
    - http-types
    - jwt
    - lens
    - lifted-base
    - map-syntax
    - mtl
    - network
    - network-api-support
    - network-uri
    - parallel-io
    - postgresql-simple
    - process
    - resource-pool
    - snap
    - snap-core
    - snap-server
    - snaplet-postgresql-simple
    - split
    - tagsoup
    - text
    - time
    - time-units
    - transformers
    - utf8-string
    - uuid
    - xmlhtml
    when:
    - condition: impl(ghc <7.10.1)
      dependencies:
      - Cabal
flags:
  development:
    description: Whether to build the server in development (interpreted) mode
    manual: false
    default: false
stability: Experimental
